### ISSUE TITLE
[DEPR]: Fully Deprecate RateXBlock

### ISSUE THREAD

**Issue by e0d** [openedx/RateXBlock#45]
### Proposal Date

18 August, 2022

### Ticket Acceptance Date

TBD

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

Olive

### Rationale

I am the [named](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Bootstrapping+Maintainership#Target-Date) maintainer of [RateXBlock](https://github.com/openedx/RateXBlock).  The code here has been updated in terms of occasionally merging requirements updates, etc.  However, the original authors intention, stated in 2016, was that this XBlock should be deprecated in favor of the [FeedbackXBlock](https://github.com/pmitros/FeedbackXBlock). 

This repository should be deprecated and removed and replaced with fork of the the FeebackXBlock.  I recommend a fork so we can ensure that it is maintained well.  I would be happy to be become the maintainer of the new fork.

### Removal

Deprecation will involve archiving [this repository](https://github.com/openedx/RateXBlock) and moving it to https://github.com/openedx-unsupported 

### Replacement

There will be some effort required to move to a different XBlock, but [FeedbackXBlock](https://github.com/pmitros/FeedbackXBlock) is a good possible replacement for this.

**Comment by kdmccormick** [comment]
@e0d I am excited for this to go away, since it's one of those annoying things [we install from GitHub instead of PyPI](https://github.com/openedx/wg-developer-experience/issues/153).

**Comment by e0d** [comment]
Planned removal this week was announced in the discourse thread, there has been no blocking feedback.  I will remove now.

**Comment by e0d** [comment]
I am closing this issue as it is stored in the repo that I am archiving, which will become read-only.
